name: Deploy bulwark app in AKS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infra/**'
      - 'README.md' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node-hostname-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}

      - name: Set up Kubernetes context
        run: |
          az aks get-credentials --resource-group bulwark-rg --name aks-weu-1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install myapp ./helm/myapp \
            --namespace bulwark-app \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/node-hostname-app \
            --set image.tag=latest
